config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

 root 'home#index'
 
  resources :lists do
    resources :items
  end

 
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
	validates_presence_of :title
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_many :lists

end

app/controllers/Users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 	def index
    @lists = List.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :list, only: [:edit, :new, :index, :show]
	before_action :item, only: [:show, :edit, :destroy, :update]


  def index
  	@items = current_user.lists.find(params[:list_id]).items
  end

  def show
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = List.find(params[:list_id]).items.new(item_params)
  	if @item.save
  		redirect_to list_path(params[:list_id])
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      if(item_params.keys.count == 1)
        key = item_params.keys.first
        if(key == "assigned" || key == "complete")
          redirect_to list_path(@item.list) and return
        end
      end
      redirect_to list_item_path(@item.list, @item)
  	else
  		render :edit
  	end
  end

  def destroy
  	@item.destroy
  	redirect_to list_path(params[:list_id])
  end

  private

  	def item_params
  		params.require(:item).permit(:title, :description, :complete, :assigned)
  	end

  	def item
  		@item = Item.find(params[:id])
  	end

  	def list
  		@list = List.find(params[:list_id])
  	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :user

  def index
    @lists = List.where(user_id:@user)
    redirect_to list_path(@lists.first)
  end

  def show
    @list = List.find(params[:id])
    @rejected = @list.items.where(complete: true, assigned: false)
  	@pending = @list.items.where(complete: false, assigned: false)
    @complete = @list.items.where(complete: true, assigned: true)
  	@incomplete = @list.items.where(complete: false, assigned: true)
    @item = @list.items.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def new
  	@list = List.new
  end

  def create
    @list = @user.lists.new(list_params)
    @list.user_id = current_user.id
  	if @list.save
  		redirect_to lists_path(@list)
  	else 
  		render :new
  	end
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
  		redirect_to list_path(@list)
  	else
  		render :edit
  	end
  end

  def destroy
  	@list.destroy
  		redirect_to lists_path
  end

  private

  def list_params
  	params.require(:list).permit(:title, :description, :user_id)
  end

  def user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<h1>Welcome, <%= current_user.first_name %>!</h1>

<% if @lists.any? %>
  <% @lists.each do |list| %>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= list.title %></span>
          <p><%= list.description %></p>
        </div>
        <div class="card-action">
            <%= link_to 'View', list_path(list), class: "btn btn-primary" %>
     		</div>
    </div>
  </div>

	     
	<% end %>

	<% else %>
		<h3>No Lists, please add one!</h3>
	<% end %>


<p><%= link_to 'Add List', new_list_path %></p>

<p><%= link_to "Edit Profile", edit_user_registration_path %></p>

<p><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: 'Really log out?'}%></p>

app/views/items/_form.html.erb
<div class="center-align container">
  <%= form_for [@list, @item], :html => { :multipart => true } do |f| %>
    <div class="row">
      <div class="input-field col s2 offset">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>

      <div class="row">
        <div class="input-field col s2 offset">
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>
     </div>

      <div class="row">
        <div class="input-field col s2 offset">
          <% if @item.persisted? %> 
            <%= f.label :complete %>
            <%= f.check_box :complete %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s2 offset">
          <% if @item.persisted? %>
            <%= f.label :assigned %>
            <%= f.check_box :assigned %>
          <% end %>
        </div>
      </div>

    <%= f.submit %>
  <% end %>
</div>

app/views/items/edit.html.erb
<h2>Edit Items</h2>

<%= render(partial: 'form') %>

app/views/items/index.html.erb
<h2><%= @list.title %> items: </h2>
<hr />

<% if @items.any? %>
  <ul>
    <% @items.each do |item| %>
      <li>
        <%= link_to item.title, list_item_path(@list, item) %>
      </li>
      <% end %>
  </ul>
<% else %>
  <h3>This list doesn't have any items!</h3>
<% end %>

<hr />

<%= link_to 'Add Item', new_list_item_path %> |

<%= link_to 'All Honey-Dew Lists', lists_path %>

app/views/items/new.html.erb
<h2>Add Items</h2>

<%= render(partial: 'form') %>

app/views/items/show.html.erb
<h2><%= @item.title %></h2>
<hr />
<h3>Description: <%=@item.description %></h3>
<h3>Completed: <%= @item.complete ? "yes" : "no" %></h3>
<h3>Assigned: <%= @item.assigned ? "yes" : "no" %></h3>



<hr>

<%= link_to 'Back to All Items', list_path(@list) %> |

<%= link_to 'Edit Item', edit_list_item_path(@list, @item) %> |

<%= link_to 'Delete Item', list_item_path, method: :delete, data: {confirm: 'Do you really want to delete this?'} %>

app/views/layouts/_navbar.html.erb
<div>
	<ul id="dropdown1" class="dropdown-content">
	  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	  <li class="divider"></li>
	  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: 'Really log out?'}%></li>
	</ul>
</div>

<nav>
  <div class="nav-wrapper">
    <span class="brand"><%= link_to "Honey Dew", root_path %></span>
    <% if current_user %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "My List", lists_path %></li>
      <li><a class="dropdown-button" href="" data-activates="dropdown1">
        <%= current_user.first_name %> <%= current_user.last_name %></a>
      </li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HoneyDew</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

<%= render 'layouts/navbar' %>

<% if flash.any? %>
	<% flash.each do |key, value| %>
	 <script>
	   Materialize.toast("<%= value %>", 4000, 'rounded left-align orange lighten-2' );
	 </script>
	<% end %>
<% end %>

<div class="container">

	<%= yield %>
</div>

</body>
</html>

app/views/lists/_form.html.erb
<div class="center-align container">
	<%= form_for @list, :html => { :multipart => true } do |f| %>

		<div class="row">
			<div class="input-field col s4 offset-s4">
			  <%= f.label :title %>
			  <%= f.text_field :title %>
		  </div>
		</div>

		<div class="row">
			<div class="input-field col s4 offset-s4">
			  <%= f.label :description %>
			  <%= f.text_field :description %>
		  </div>
	  </div>

	  <%= f.submit %>
	<% end %>
</div>

app/views/lists/edit.html.erb
<h1>Add List</h1>

<%= render(partial: 'form') %>

app/views/lists/index.html.erb
<h2>Lists</h2>


<% if @lists.any? %>
  <ul>
    <% @lists.each do |list| %>
    <li>
    <%= link_to list.title, list_path(list) %>
    </li>
    <% end %>
  </ul>
  <% else %>
  <h3>No Lists!</h3><br>
  <%= link_to 'Add List', new_list_path %>
<% end %>

<hr />


<%= link_to 'Back', root_path %>

app/views/lists/new.html.erb
<h1>Add List</h1>


<%= render(partial: 'form') %>

app/views/lists/show.html.erb
<h1>List</h1>
<p>Title: <%= @list.title %></p>
<p>Description: <%= @list.description %></p>

<%= link_to 'Edit List', edit_list_path(@list) %> |

<%= link_to 'All Lists', lists_path %>

<hr>

<%if @list.items.any? %>
  <h3>Incomplete Items:</h3>
    <% if @incomplete.any? %>
      <% @incomplete.each do |item| %>
        <ul>
          <li>
            <%= link_to item.title, list_item_path(@list, item) %><br>
          </li>
       </ul>
      <% end %>
    <% else %>
      <h5>Please add something!</h5>
    <% end %>

  <h3>Completed Items:</h3>
    <% if @complete.any? %>
      <% @complete.each do |item| %>
        <ul>
          <li>
            <%= link_to item.title, list_item_path(@list, item) %><br>
          </li>
        </ul>
      <% end %>
    <% else %>
      <h5>Nothing, get out there and do something!</h5>
    <% end %>

  <h3>Pending Items:</h3>
    <% if @pending.any? %>
      <% @pending.each do |item| %>
        <ul>
          <li>
            <%= link_to item.title, list_item_path(@list, item) %> 
          </li>

          <% if current_user.id == @list.user_id %>
            <%= form_for [@list, item] do |f| %>
     					<%= f.hidden_field :assigned, value: true %>
   						<%= f.submit 'Accept' %>
   					<% end %>
   					<%= form_for [@list, item] do |f| %>
     					<%= f.hidden_field :complete, value: true %>
    				 	<%= f.submit 'Reject' %>
   					<% end %>
          <% end %>

        </ul>
      <% end %>
    <% else %>
      <h5>Nothing, please add something!</h5>
    <% end %>


  <h3>Rejected Items:</h3>
    <% if @rejected.any? %>
      <% @rejected.each do |item| %>
        <ul>
          <li>
            <%= link_to item.title, list_item_path(@list, item) %><br>
          </li>
        </ul>
      <% end %>
    <% else %>
      <h5>Nothing, please add something!</h5>
    <% end %>

<% else %>
  <h3>Please add something:</h3>
<% end %>


<hr>

<h3>Add New Item:</h3>

<%= render(partial: 'items/form') %>